In [1]:
import spacy
import pandas as pd

In [2]:
nlp = spacy.load('en_core_web_sm')

##### import data

In [3]:
df = pd.read_csv('../data/bbc_news.csv')
df.head(2)

,Unnamed: 0,index,title,pubDate,guid,link,description
0,0,6684,Can I refuse to work?,"Wed, 10 Aug 2022 15:46:18 GMT",https://www.bbc.co.uk/news/business-62147992,https://www.bbc.co.uk/news/business-62147992?a...,With much of the UK enduring another period of...
1,1,9267,'Liz Truss the Brief?' World reacts to UK poli...,"Mon, 17 Oct 2022 11:35:12 GMT",https://www.bbc.co.uk/news/world-63285480,https://www.bbc.co.uk/news/world-63285480?at_m...,The UK's political chaos has been watched arou...

In [4]:
text = ' '.join(df['title'] + '. ' + df['description']) # convert pandas series inside the parantheses to a single long string
print(text[:200])

Can I refuse to work?. With much of the UK enduring another period of hot weather, some workers will face very high temperatures. 'Liz Truss the Brief?' World reacts to UK political turmoil. The UK's

In [5]:
doc = nlp(str(text))

> spacy should usually be fed raw text

> spacy tokenizes text, gives POS and NER tags, ...

##### Named Entitiy Recognition

In [6]:
from spacy import displacy

displacy.render(doc[:100], style = 'ent')

In [7]:
ner_df = pd.DataFrame(columns = ['token', 'tag'])

for word in doc.ents:
    ner_df.loc[len(ner_df)] = [word.text, word.label_]

ner_df.head()

         token       tag
0           UK       GPE
1    Liz Truss    PERSON
2           UK       GPE
3           UK       GPE
4  superyachts  CARDINAL

In [8]:
ner_df_grouped = ner_df.value_counts(['token', 'tag']).sort_values(ascending = False).reset_index(name = 'count') # group by token and tag

ner_df_grouped.head(10)

     token       tag  count
0  England       GPE     95
1       UK       GPE     83
2  Ukraine       GPE     82
3    first   ORDINAL     56
4       US       GPE     50
5  Russian      NORP     40
6      one  CARDINAL     37
7      BBC       ORG     35
8   Russia       GPE     25
9    China       GPE     22

In [9]:
ner_df_grouped[ner_df_grouped['tag'] == 'GPE'].head(10)

        token  tag  count
0     England  GPE     95
1          UK  GPE     83
2     Ukraine  GPE     82
4          US  GPE     50
8      Russia  GPE     25
9       China  GPE     22
13  Australia  GPE     21
14     France  GPE     20
15      India  GPE     18
17     London  GPE     17

##### Part of Speech tagging

In [10]:
pos_df = pd.DataFrame(columns = ['token', 'tag'])

for token in doc:
    pos_df.loc[len(pos_df)] = [token.text, token.pos_]

pos_df.head()

    token   tag
0     Can   AUX
1       I  PRON
2  refuse  VERB
3      to  PART
4    work  VERB

In [11]:
pos_df_grouped = pos_df.value_counts(['token', 'tag']).sort_values(ascending = False).reset_index(name = 'count') # group by token and tag

pos_df_grouped.head()

  token    tag  count
0     .  PUNCT   1962
1   the    DET    999
2    of    ADP    593
3    in    ADP    566
4     :  PUNCT    545

In [12]:
pos_df_grouped[pos_df_grouped['tag'] == 'NOUN'].head(10)

      token   tag  count
50   people  NOUN     57
60      war  NOUN     53
65     year  NOUN     52
79    years  NOUN     37
80     time  NOUN     37
86      win  NOUN     34
91   police  NOUN     32
97      day  NOUN     31
106  record  NOUN     26
109   world  NOUN     25

####